### ISSUE TITLE
 warning:  device/xiaomi/odin/lineage_odin.mk includes non-existent modules in PRODUCT_PACKAGES

### ISSUE THREAD

**Issue by ketanpatel25** [Inkypen79/device_xiaomi_odin#6]
[100% 1/1] initializing build system ...
Adding CUSTOM_LOCALES [ast_ES gd_GB cy_GB fur_IT] to PRODUCT_LOCALES [en_US en_US af_ZA am_ET ar_EG ar_XB as_IN az_AZ be_BY bg_BG bn_BD b
s_BA ca_ES cs_CZ da_DK de_DE el_GR en_AU en_CA en_GB en_IN en_XA es_ES es_US et_EE eu_ES fa_IR fi_FI fr_CA fr_FR gl_ES gu_IN hi_IN hr_HR 
hu_HU hy_AM in_ID is_IS it_IT iw_IL ja_JP ka_GE kk_KZ km_KH kn_IN ko_KR ky_KG lo_LA lt_LT lv_LV mk_MK ml_IN mn_MN mr_IN ms_MY my_MM nb_NO
 ne_NP nl_NL or_IN pa_IN pl_PL pt_BR pt_PT ro_RO ru_RU si_LK sk_SK sl_SI sq_AL sr_Latn_RS sr_RS sv_SE sw_TZ ta_IN te_IN th_TH tl_PH tr_TR
 uk_UA ur_PK uz_UZ vi_VN zh_CN zh_HK zh_TW zu_ZA en_XC]
[ 99% 185/186] finishing build rules ...
FAILED: 
build/make/core/main.mk:1312: warning:  device/xiaomi/odin/lineage_odin.mk includes non-existent modules in PRODUCT_PACKAGES
Offending entries:
android.hardware.nfc-service.nxp
android.hardware.wifi-service
libprotobuf-cpp-full-3.9.1-vendorcompat
libprotobuf-cpp-lite-3.9.1-vendorcompat
build/make/core/main.mk:1312: error: Build failed.
10:06:05 ckati failed with: exit status 1

please provide help

**Comment by xc112lg** [comment]
were you able to fix this?
